version: '3.8'

networks:
  dev:

services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev
  
  app:
    build: .
    container_name: url-shortener
    command: ["python", "-m", "src.main"]
    ports:
      - "8888:8000"
    depends_on:
      - db
    environment:
      DB_PATH: postgresql+asyncpg://admin:password@db:5432/url-db
      DB_ECHO: 1
      API_PATH: /v1
    networks:
      - dev

volumes:
  postgres_data: